site_name: TFE
site_url: 'https://hterminasyan.github.io/TFE/' # required for working 404 page
repo_name: 'hterminasyan/TFE'
repo_url: 'https://github.com/hterminasyan/TFE'
docs_dir: 'docs' # default
site_dir: 'site' # default
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'blue'
nav:
    - Home: index.md
    - About: about.md
    - Onboarding:
      - Overview: onbording/onbording.md
    - Integration:
      - Starter Kit: integration/starterkit.md
      - Hands-on Setup and examples with API Management: integration/apimng.md
      - Hands-on CPI: integration/cpi.md
      - Hands-on Open Connectors: integration/openconnectors.md
      - Use Case: integration/usecase.md
    - Extension:
      - Starter Kit: extension/starterkit.md
      - Hands-on Set-up & examples with CAP : extension/extension1.md
      - Hands-on Set-up & examples with Kyma Runtime : extension/extension2.md
      - Hands-on Set-up & examples with ABAP Runtime : extension/extension3.md
      - Use Case: extension/usecase.md
    - Data Mgmt & Analytics:
      - Starter Kit: data_mgmt_analytics/starterkit.md
      - Hands-on Modeling: data_mgmt_analytics/analytics.md
      - Hands-on Setup and examples with data integration/federation: data_mgmt_analytics/datamgmt.md
      - Use Case: data_mgmt_analytics/usecase.md

plugins:
  - search
  - minify:
      minify_html: true

markdown_extensions:
  - admonition
  - attr_list
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  # PyMdown Extensions Documentation: https://facelessuser.github.io/pymdown-extensions/extensions/betterem/
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.keys
  - pymdownx.smartsymbols
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.caret