site_name: TFE
site_url: 'https://hterminasyan.github.io/TFE/' # required for working 404 page
repo_name: 'hterminasyan/TFE'
repo_url: 'https://github.com/hterminasyan/TFE'
docs_dir: 'docs' # default
site_dir: 'site' # default
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'blue'